# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.31

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/kyoko/src/processing-code/cpp_version

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/kyoko/src/processing-code/cpp_version/build

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/kyoko/src/processing-code/cpp_version/build/CMakeFiles /home/kyoko/src/processing-code/cpp_version/build//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/kyoko/src/processing-code/cpp_version/build/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named processing3d

# Build rule for target.
processing3d: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 processing3d
.PHONY : processing3d

# fast build rule for target.
processing3d/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/processing3d.dir/build.make CMakeFiles/processing3d.dir/build
.PHONY : processing3d/fast

Grid.o: Grid.cpp.o
.PHONY : Grid.o

# target to build an object file
Grid.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/processing3d.dir/build.make CMakeFiles/processing3d.dir/Grid.cpp.o
.PHONY : Grid.cpp.o

Grid.i: Grid.cpp.i
.PHONY : Grid.i

# target to preprocess a source file
Grid.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/processing3d.dir/build.make CMakeFiles/processing3d.dir/Grid.cpp.i
.PHONY : Grid.cpp.i

Grid.s: Grid.cpp.s
.PHONY : Grid.s

# target to generate assembly for a file
Grid.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/processing3d.dir/build.make CMakeFiles/processing3d.dir/Grid.cpp.s
.PHONY : Grid.cpp.s

Obstacle.o: Obstacle.cpp.o
.PHONY : Obstacle.o

# target to build an object file
Obstacle.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/processing3d.dir/build.make CMakeFiles/processing3d.dir/Obstacle.cpp.o
.PHONY : Obstacle.cpp.o

Obstacle.i: Obstacle.cpp.i
.PHONY : Obstacle.i

# target to preprocess a source file
Obstacle.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/processing3d.dir/build.make CMakeFiles/processing3d.dir/Obstacle.cpp.i
.PHONY : Obstacle.cpp.i

Obstacle.s: Obstacle.cpp.s
.PHONY : Obstacle.s

# target to generate assembly for a file
Obstacle.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/processing3d.dir/build.make CMakeFiles/processing3d.dir/Obstacle.cpp.s
.PHONY : Obstacle.cpp.s

UserInput.o: UserInput.cpp.o
.PHONY : UserInput.o

# target to build an object file
UserInput.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/processing3d.dir/build.make CMakeFiles/processing3d.dir/UserInput.cpp.o
.PHONY : UserInput.cpp.o

UserInput.i: UserInput.cpp.i
.PHONY : UserInput.i

# target to preprocess a source file
UserInput.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/processing3d.dir/build.make CMakeFiles/processing3d.dir/UserInput.cpp.i
.PHONY : UserInput.cpp.i

UserInput.s: UserInput.cpp.s
.PHONY : UserInput.s

# target to generate assembly for a file
UserInput.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/processing3d.dir/build.make CMakeFiles/processing3d.dir/UserInput.cpp.s
.PHONY : UserInput.cpp.s

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/processing3d.dir/build.make CMakeFiles/processing3d.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/processing3d.dir/build.make CMakeFiles/processing3d.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/processing3d.dir/build.make CMakeFiles/processing3d.dir/main.cpp.s
.PHONY : main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... processing3d"
	@echo "... Grid.o"
	@echo "... Grid.i"
	@echo "... Grid.s"
	@echo "... Obstacle.o"
	@echo "... Obstacle.i"
	@echo "... Obstacle.s"
	@echo "... UserInput.o"
	@echo "... UserInput.i"
	@echo "... UserInput.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

